language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10

script:
  - npm i
  - npm run bower -- install

stages:
  - docker

jobs:
  include:
    - stage: docker
      language: bash
      sudo: required
      services:
        - docker
      script: docker build . -t bower-npm-resolver-inside-docker
